### ISSUE TITLE
array operations

### ISSUE THREAD

**Issue by Saiesh-Agre** [Chinmay-03/Hactoberfest-X-MIBCS-2022#146]
To create array and perform operations on it.

Operations:
1. Read an array
2. Display an array
3. Insertion
4. Deletion
5. Update element
6. Search for an element
7. Sorting 
8. Merging

**Comment by Chinmay-03** [comment]
@Saiesh-Agre ask collaborator to comment on the issue

**Comment by Darshk03** [comment]
@Chinmay-03 Please assign me.

**Comment by ankitkumar0622** [comment]
Hi can you please assign this to me, i would like to work on this.

**Comment by Chinmay-03** [comment]
> Hi can you please assign this to me, i would like to work on this.
> 

Yes you can submit code with proper problem statement,  issue no , in uploads file

**Comment by Kritiji** [comment]
Heyy.. I can do this in Java/c..  please assign this task to me

**Comment by ankitkumar0622** [comment]
Hi , I have made a pull request can you please have a look .

**Comment by Chinmay-03** [comment]
> 

Yes you can submit code with proper problem statement, issue no , in uploads file

**Comment by Chinmay-03** [comment]
> Heyy.. I can do this in Java/c.. please assign this task to me

Yes you can submit code with proper problem statement, issue no , in uploads file

**Comment by Chinmay-03** [comment]
> Hi , I have made a pull request can you please have a look .

@ankitkumar0622  congrats merged!
