### ISSUE TITLE
Solve the errors in json file

### ISSUE THREAD

**Issue by Chinmay-03** [Chinmay-03/Hactoberfest-X-MIBCS-2022#198]
https://github.com/Chinmay-03/Hactoberfest-X-MIBCS-2022/blob/main/Aboutme.json
https://github.com/Chinmay-03/Hactoberfest-X-MIBCS-2022/blob/main/Quotes.json

**Comment by javamultiplex** [comment]
I would like to work on this. Please assign to me

**Comment by Chinmay-03** [comment]
> @Chinmay-03 - I would like to work on this. Please assign to me

@javamultiplex go ahead!
