### ISSUE TITLE
Add Greetings GitHub Actions to the Project .

### ISSUE THREAD

**Issue by SaumyaBhushan** [Chinmay-03/Hactoberfest-X-MIBCS-2022#211]
**Is your feature request related to a problem? Please describe.**
No, it's not related to a problem, but we can add a GitHub Actions for greeting.

**Describe the solution you'd like**
Whenever a new pull request is created by new user it will welcome them to the project

**Describe alternatives you've considered**

**Additional context**

**Comment by SaumyaBhushan** [comment]
@Chinmay-03 can you please assign it to me ?

**Comment by Chinmay-03** [comment]
@SaumyaBhushan go ahead! Do it ASAP

**Comment by SaumyaBhushan** [comment]
@Chinmay-03 Please review.
