### ISSUE TITLE
freedom to chose type of sorting

### ISSUE THREAD

**Issue by SOURABH2403** [Chinmay-03/Hactoberfest-X-MIBCS-2022#213]
In the project of sorting, sorting is done in ascending order of numbers.
It has two methods of sorting:-
    - bubble sorting
    - selection sorting (here each number is compared with all numbers present in the list)
So user should be able to make choice whether he wants sorting by bubble shorting or selection sorting

**Comment by pritam1309** [comment]
can you assigned it to me with proper labels

**Comment by pritam1309** [comment]
i made quick sort #222 plz merge it
