### ISSUE TITLE
write what we do.md file for this repository

### ISSUE THREAD

**Issue by Chinmay-03** [Chinmay-03/Hactoberfest-X-MIBCS-2022#217]
you should explore this repository to understand what it does and write a file name what_we_do.md
to help a newbie, or first-time visitor more easily understand this repository and help it make more popular.

**Multiple people can be assigned and can collaborate**

**Comment by Avaneesh-dev** [comment]
Assign this issue to me, I will try my best to contribute.

**Comment by Chinmay-03** [comment]
> Assign this issue to me, I will try my best to contribute.

@Avaneesh-dev  go ahead! take your time. come up with a good contribution

**Comment by Avaneesh-dev** [comment]
I have raised a pull request which fixes this issue and I have tagged this issue with my pull request with appropriate title. Thank you for this opportunity to contribute.
