### ISSUE TITLE
how to write a issue

### ISSUE THREAD

**Issue by Chinmay-03** [Chinmay-03/Hactoberfest-X-MIBCS-2022#5]
🐞 **Problem**

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

*   Comment below about what you've started working on.
*   Add, commit, push your changes.
*   Submit a pull request and add this in comments - `Addresses #<put issue number here>`
*   Ask for reviews in comments section of pull request.
*   Celebrate your contribution to this project. 🎉

**Comment by Kishubhai** [comment]
Hii Please assign me this project.I wanna work in this project
